# This is file is used to help customize TSDB documentation building process on ReadTheDocs.

version: 2

formats:
    - htmlzip
    - pdf
    - epub

sphinx:
    configuration: docs/conf.py
    fail_on_warning: false

build:
    os: ubuntu-22.04

    tools:
        python: "3.10"

    jobs:
        pre_install:
            - python -m pip install --upgrade pip
            - pip install pandas numpy scipy scikit-learn
            - pip install sphinx==6.2.1 docutils==0.19 sphinxcontrib-bibtex==2.1.4 sphinxcontrib-gtagjs sphinx-autodoc-typehints furo==2023.07.26

        post_install:
            - pip install docutils==0.20
            # this version fixes issue#102, put it in post_install to avoid being
            # overwritten by other versions (like 0.19) while installing other packages
