name: Linting

on:
    push:
        branches:
            - main
            - dev
    pull_request:
        branches:
            - dev

jobs:
    flake8-linting:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"

            - name: Install Flake8
              run: |
                pip install flake8 flake8-pyproject

            - name: Run linting
              run: |
                flake8 .
