# This workflow will automatically publish a Python package to PyPI using Twine when a release is created
# For more information, please refer to
# https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish to PyPI

on:
  push:
    branches:
      - release

  release:
    types: [published]

permissions:
  contents: read

jobs:
  PyPI-deployment:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        check-latest: true
        cache-dependency-path: |
          requirements.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build wheel
        pip install -r requirements.txt

    - name: Fetch the test environment details
      run: |
        which python
        pip list

    - name: Build package
      run: |
        python -m build --no-isolation

    - name: Publish the new package to PyPI
      uses: pypa/gh-action-pypi-publish@v1.8.7
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
